### ISSUE TITLE
The "links" array isn't empty but has `null` item for `/collections`

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-earthengine-driver#12]
For the `/processes` endpoint, the `links` item is an empty array: `[]`. That's fine.
But for `/collections`, it's an array with a `null` item: `[null]`. That probably shouldn't be the case.

Edit: I'm referring to the currently deployed instance, i.e. http://giv-openeo.uni-muenster.de:8080/v0.3/collections -- not sure whether that is the most recent version -> sorry if this is already fixed in some branch.

**Comment by m-mohr** [comment]
Thanks and fixed, see commit above.
