### ISSUE TITLE
Swap bands B4 and B8, because non-sensical NDVI result

### ISSUE THREAD

**Issue by glemoine62** [Open-EO/openeo-earthengine-driver#32]
You need to swap B4 and B8 (B8 should be b1, B4 should be b2) because the normallized difference is calculated as (b1-b2)/(b1+2).

**Comment by m-mohr** [comment]
Hi @glemoine62,

thanks for reporting. You are only referring to the examples in the README, right? Indeed, the example is incorrect. I'll update it.

**Comment by glemoine62** [comment]
Yes, correct. I parsed the JavaScript result. However, it logically follows from the process graph.

**Comment by m-mohr** [comment]
Thanks, I fixed that. 

Note that this example is not very performant and will change soon as we have found better and more performant ways to implement this with the new API version. I'll update example and implementation in the next weeks.
