### ISSUE TITLE
Cannot upload a file into a subfolder

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-earthengine-driver#39]
Hey,

I just tried to upload a file into a custom subfolder like `/subfolder/test.json`. I get a 404 back with a HTML. Uploading a file into the top level folder works without problems.

API version 1.0.0-rc.2

**Comment by m-mohr** [comment]
Hey, in Postman it's working for me. What's the exact HTTP request you are doing?

**Comment by flahn** [comment]
```
PUT https://earthengine.openeo.org/v1.0/files/subfolder%2Ftest%2Ejson
Headers:
                                                              
Accept        application/json, text/xml, application/xml, */*
Content-Type                          application/octet-stream
Authorization                          Bearer ****
```

I guess then the url encoding is the issue. Thanks

**Comment by m-mohr** [comment]
Yes, path must not be URL encoded according to the API spec. :-)
