### ISSUE TITLE
Duplicated entries in users.db

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-earthengine-driver#4]
On my system, the file `/storage/users.db` contains the same line a couple hundred times. According to @m-mohr, one line is added every time a user logs in or changes their credentials - despite calling the `update` function... Strange.

**Comment by m-mohr** [comment]
According to the NeDB maintainer it is working as expected, see 
* https://github.com/louischatriot/nedb/issues/527
* https://github.com/louischatriot/nedb/issues/530
I'll set a auto-compaction interval of an hour or so to make sure the database doesn't get overly large.
