### ISSUE TITLE
Not found: placeholder %s in message

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-earthengine-driver#42]
```
$ curl 'https://earthengine.openeo.org/v1.0/foobar'
{"id":"1591600271210",
"code":"NotFound",
"message":"%s does not exist",
"url":"https://open-eo.github.io/openeo-api/errors/#openeo-error-codes"}
```

message has unrreplaced placeholder `%s`

**Comment by m-mohr** [comment]
Thanks for the report. Weird, the code doesn't have a placeholder in the API's errors.json file. This is somehow leaking through from the server software restify. Implemented a workaround in the commit above. Will be updated on the server in some days.
