### ISSUE TITLE
Collections listed twice

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-earthengine-driver#45]
As discovered in Open-EO/openeo-hub#76, the GEE driver currently outputs the collection `COPERNICUS/S2_SR` twice in its `/collections` response ([live link](https://earthengine.openeo.org/v1.0/collections), compare indices 19 and 49). I don't know whether this error happens on the GEE or the driver side, but in any case you might want to put in a little line of code that prevents this from happening as clients may rely on the ID being "A unique identifier for the collection" (quoted from [the API spec](https://openeo.org/documentation/1.0/developers/api/reference.html#operation/list-collections)).

**Comment by m-mohr** [comment]
Interesting, I'll check that. GEE recently had some invalid files in the GCS and refresing from source didn't help. So I'll need to check in code....
