### ISSUE TITLE
Error when requesting log shortly after starting a batch job

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-earthengine-driver#51]
When a batch job is started and almost immediately the log is requested, then there is an error that the .db file was not created.

> Server error: ENOENT: no such file or directory, rename 'storage/job_files/cZ2ND0Z5nhBFNQFq/logs.db~' -> 'storage/job_files/cZ2ND0Z5nhBFNQFq/logs.db

(group7, job_id: cZ2ND0Z5nhBFNQFq)

Maybe sent the HTTP 200 when starting the job after the log file has initialized or initialize the log upon creating the job.

**Comment by m-mohr** [comment]
It is implemented like you suggested, but it seems there's an issue with the database driver in the background. Maybe has to do with concurrent requests or so... not exactly sure yet. Is also present when the services run and XYZ tiles are requested and logs are simultaneously requested, too.

**Comment by m-mohr** [comment]
@flahn I implemented some tweak. Could you please check whether the situation has improved?

**Comment by flahn** [comment]
now an empty log is returned, which is what to be expected. Thanks.
