### ISSUE TITLE
sample graph for climatological_normal

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-earthengine-driver#57]
Hi Matthias,

I've just found out the interesting process _climatological_normal_ implemented in GEE back-end, which I think could be useful for a vegetation analysis we will have to perform with OpenEO.
Could you please provide me a minimal working example with this process? I've tried something really dumb like this but it didn't work (error 500 adding batch job).
```

{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "COPERNICUS/S2",
        "spatial_extent": {
          "west": 11.396212577819824,
          "south": 46.32387525280791,
          "east": 11.446423530578613,
          "north": 46.34674986605978
        },
        "temporal_extent": [
          "2016-01-01T00:00:00Z",
          "2019-12-31T23:59:59Z"
        ],
        "bands": [
          "B8"
        ]
      }
    },
    "2": {
      "process_id": "climatological_normal",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "frequency": "daily",
        "climatology_period": [
          "2016-01-01T00:00:00Z",
          "2019-12-31T23:59:59Z"
        ]
      }
    },
    "3": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "2"
        },
        "format": "GTIFF-THUMB"
      },
      "result": true
    }
  }
}
```

**Comment by m-mohr** [comment]
Here are examples for web services on GEE: 
- ERA5 monthly: https://github.com/Open-EO/openeo-earthengine-driver/blob/master/docs/era5-monthly-anomalies.json
- ERA5 daily: https://github.com/Open-EO/openeo-earthengine-driver/blob/master/docs/era5-daily-anomalies.json
