### ISSUE TITLE
save_result and palette option

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-earthengine-driver#58]
After trying the sample process graph with climatological_normal, I've noticed that in the [process graph](climatological_normal) there's save_result with the palette option, how do you actually apply this? I do not understand what is mapping with 0 -> #2166AC 1 -> #4393C3 . Is the value 0 in the result mapped to the color #2166AC? What to do with values which are not mapped with a color?

![image](https://user-images.githubusercontent.com/31700619/95332875-492cc500-08ac-11eb-8785-c8849ce8bb9e.png)

_Originally posted by @clausmichele in https://github.com/Open-EO/openeo.org/issues/8#issuecomment-704914272_

**Comment by m-mohr** [comment]
We just pass that to GEE, so their docs apply: https://developers.google.com/earth-engine/guides/image_visualization#color-palettes

AFAIK is just creates a color gradient between the minimum and maximum using the given hex values, so there's not really direct mapping between values.

**Comment by clausmichele** [comment]
Ok, so it's not a functionality which is defined by save_result but only a specific feature you can offer using GEE.

**Comment by m-mohr** [comment]
Yes, file formats are all back-end dependent and not standardized.
