### ISSUE TITLE
ERA5 UC web service on deployed server gives "waiting for socket"

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-earthengine-driver#59]
I recently had it that when I was running the ERA5 use case (monthly I think), the deployed service at earthengine.openeo.org doesn't load any longer and requests in the browser just show "waiting for socket" or something similar.

I should check how well multiple parallel requests work before the workshop...

**Comment by jwagemann** [comment]
Is this a problem related to EarthEngine? Let me know  if can help anyhow.

**Comment by m-mohr** [comment]
@jwagemann Thanks for asking. I'm relatively sure this is an issue in my server implementation and has nothing to do with GEE or the ERA5 use case in general. So nothing to do from your side. :-)
