### ISSUE TITLE
aggregate_temporal_frequency difference with aggregate_temporal_period

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-earthengine-driver#60]
I would like to know the difference between _aggregate_temporal_frequency_ which is available in GEE compared to _aggregate_temporal_period_ in the API. I would like to implement it also in the opendatacube back-end and I was looking for the correct one. From the description it seems only a different name for the same process.

**Comment by m-mohr** [comment]
GEE was the first back-end to implement aggregate_temporal_frequency. When we started to standardize it and move it to the processes repository, we changed the name and parameters from frequency to period. Unfortunately, I never managed to update the GEE implementation. I'll look into that after the user workshop and update the implementation and examples accordingly. There should be no functional difference except that the names are different and other values for the parameters may be (un)supported.
