### ISSUE TITLE
missing logical operators

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-earthengine-driver#65]
In EURAC use case, we use logical operators such as and, or, not, lt, gt and so on.
Do you plan to implement them? How much effort would it be for you?
I was trying to see if it was possible to run our use case on other backends for D35 and this is the main limit at the moment, unavailable data comes next.

**Comment by m-mohr** [comment]
Not planned at the moment due to time constraints and limited funding.

**Comment by m-mohr** [comment]
Implemented
