### ISSUE TITLE
Implement Authentication via OAuth/OIDC

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-earthengine-driver#82]
Users should be able to connect with their own accounts, not with our service account.

**Comment by edzer** [comment]
> Users should be able to connect with their own accounts, not with out service account.

Did you mean "with our service account", or "without service account"?

**Comment by m-mohr** [comment]
Oh, "with our". Working on it right now :-)

**Comment by m-mohr** [comment]
A basic implementation is available in the repository. It generally works, but has some drawbacks:

1. A refresh_token is not available to the openEO proxy -> The access_token may expire for longer running requests, but may only be an issue with updating the job status.
2. The only flow that is supported by Google and doesn't require a client secret seems to be `implicit`. That means only the Web Editor can connect easily, all other clients will need client secret that users obtain from the Google API Console.

Keeping these points open for now as they are lower priority for me for now. I might be able to weaken the effects for (1) through additional code and (2) needs to wait for improvements on Googles side, which I heard are at least planned.
